description: >
    Implement to provide USBController attributes.
properties:
    - name: Name
      type: string
      flags:
          - readonly
      description: >
          The name of the resource or array member.
    - name: Id
      type: string
      flags:
          - readonly
      description: >
          The unique identifier for this resource within the 
          collection of similar resources.
    - name: Description
      type: string
      flags:
          - readonly
      description: >
          Implementation form for the USBController device..
    - name: Manufacturer
      type: string
      flags:
          - readonly
      description: >
          The manufacturer of this USB controller.
    - name: Model
      type: string
      flags:
          - readonly
      description: >
          The product model number of this USB controller.
    - name: PartNumber
      type: string
      flags:
          - readonly
      description: >
          The part number for this USB controller..
    - name: SKU
      type: string
      flags:
          - readonly
      description: >
          The SKU for this USB controller..
    - name: SerialNumber
      type: string
      flags:
          - readonly
      description: >
          The serial number for this USB controller..
    - name: Links
      type: string
      flags:
          - readonly
      description: >
          Links for the PCIeDevices..
    - name: State
      type: string
      flags:
          - readonly
      description: >
          The State of the USB Controller.
    - name: Health
      type: string
      flags:
          - readonly
      description: >
          Health of the USB Controller.
