description: >
    Implement a method and property for updating the Bios Password from OOB
methods:
    - name: SetPassword
      description: >
          Method to set Bios password from OOB.
      parameters:
          - name: PasswordName
            type: string
            description: >
                The name of the Bios password type which is set.
          - name: CurrentPassword
            type: string
            description: >
                The current password for this password type.
          - name: NewPassword
            type: string
            description: >
                The new password which needs be set for this password type.
      errors:
          - xyz.openbmc_project.Common.Error.InternalFailure
          - xyz.openbmc_project.Common.Error.NotAllowed

properties:
    - name: BiosPasswordUpdateNotify
      type: boolean
      default: false
      description: >
          The notify whether the Bios password id updated from OOB.
