description: >
    Implement to provide system specific network configuration features.
properties:
    - name: HostName
      type: string
      description: >
          The value of this property shall be host name of the system.
      errors:
          - xyz.openbmc_project.Common.Error.InvalidArgument
    - name: InterfaceCount
      type: byte
      flags:
          - readonly
      description: >
          The value of this property shall show the number of network interface

