description: >
  This defines a Microsemi RAID controller configuration methods

methods:
  - name: CreateLogicalDrive
    parameters:
    - name: Name
      type: string
    - name: RaidLevel
      type: enum[com.ami.storage.mscc.ctrl.LogicalDrive.RaidType]
    - name: ArrayNumber
      type: uint16
    - name: PdList
      type: array[uint16]
    - name: StripSize
      type: uint64
    - name: Size
      type: uint64
    - name: ParityGroupCount
      type: byte
    - name: Accelerator
      type: enum[com.ami.storage.mscc.ctrl.LogicalDrive.LdAccelerator]
    returns:
      - name: MessageId
        type: uint64
    errors:
      - com.ami.storage.Common.Error.InvalidArgument
      - com.ami.storage.Common.Error.InternalFailure
      - com.ami.storage.Common.Error.DeviceOrResourceBusy

  - name: DeleteLogicalDrive
    parameters:
      - name: LdId
        type: uint16
    returns:
      - name: MessageId
        type: uint64
    errors:
      - com.ami.storage.Common.Error.InvalidArgument
      - com.ami.storage.Common.Error.InternalFailure
      - com.ami.storage.Common.Error.DeviceOrResourceBusy

signals:
    - name: MethodCompletedSignal
      description: >
        Signal indicating about the status of async dbus method call.
      properties:
        - name: Identification
          type: uint64
          description: >
            Unique identification of each method call.
        - name: ErrorCode
          type: enum[com.ami.storage.Common.ErrorCode]
        - name: What
          type: string
          description: >
            The details about the error.